DECLARE @AccountID BIGINT

SET @ACCOUNTID=6813027

--Order Payment Transaction
/*- As Per 1464 , in case of multiple payment entries for a order , max of the entry is migrated and total amount is put on that selected profile.
Most of the difference in number of payment profile below is for that reason*/
SELECT P_RFACCOUNTID,PK , RF_PAY_CNT , HYB_PAY_CNT FROM 
(SELECT COUNT(*) HYB_PAY_CNT,U.p_rfaccountid , O.PK
FROM HYBRIS.DBO.PAYMENTTRANSACTIONS PT,
HYBRIS.DBO.ORDERS O ,
HYBRIS.DBO.USERS U
WHERE PT.P_ORDER=O.PK AND 
U.P_SOURCENAME='Hybris-DM' AND U.PK=O.USERPK AND
U.P_RFACCOUNTID=CAST(@AccountID AS NVARCHAR) AND
O.TYPEPKSTRING <>8796127723602
GROUP BY U.p_rfaccountid , O.PK ) HYB,
--RF PAYMENT COUNT
(SELECT COUNT(*) RF_PAY_CNT,A.ACCOUNTID , O.ORDERID
FROM
RFOPERATIONS.HYBRIS.ORDERPAYMENT OP,
rfoperations.HYBRIS.ORDERS O,
rfoperations.ETL.ORDERDATE D,
rfoperations.RFO_ACCOUNTS.ACCOUNTBASE A
WHERE O.ORDERID=D.ORDERID AND A.ACCOUNTID=@AccountID AND A.COUNTRYID=236 AND
O.ACCOUNTID=A.ACCOUNTID AND CAST(O.ACCOUNTID AS NVARCHAR) IN (SELECT P_RFACCOUNTID FROM HYBRIS.DBO.USERS WHERE P_SOURCENAME='Hybris-DM') 
AND O.ORDERID=OP.ORDERID AND D.STARTDATE>'2014-05-01 00:00:00.00'
GROUP BY A.ACCOUNTID , O.ORDERID) RF
WHERE RF.ACCOUNTID=P_RFACCOUNTID AND RF.ORDERID=HYB.PK 
--AND RF_PAY_CNT <>HYB_PAY_CNT
