DECLARE @AccountID BIGINT

SET @ACCOUNTID=6813027

--Autoship Cancel / Delay log

SELECT RF_ASCD_CNT,HYB_ASCD_CNT , RF.ACCOUNTID,RF.STATUS
FROM
(SELECT COUNT(*) RF_ASCD_CNT, ADC.ACCOUNTID,STATUS FROM 
RFOperations.Logging.autoshipDelayCancellationLog ADC,
RFOPERATIONS.RFO_ACCOUNTS.ACCOUNTBASE AB 
WHERE ADC.ACCOUNTID=AB.ACCOUNTID AND  AB.COUNTRYID=236 AND
AB.ACCOUNTID=@AccountID AND
CAST(AB.ACCOUNTID AS NVARCHAR) IN (SELECT P_RFACCOUNTID FROM HYBRIS.DBO.USERS WHERE P_SOURCENAME='Hybris-DM')
GROUP BY ADC.ACCOUNTID,STATUS ) RF,
(SELECT P_RFACCOUNTID , p_status,COUNT(*) HYB_ASCD_CNT FROM
HYBRIS.DBO.AUTOSHIPLOGS WHERE P_STATUS IN ('Cancel','Delay') AND
CAST(@AccountID as NVARCHAR)=p_rfaccountid
GROUP BY P_RFACCOUNTID , p_status ) HYB
WHERE CAST(RF.ACCOUNTID AS NVARCHAR)=HYB.P_RFACCOUNTID AND RF.STATUS=P_STATUS
