DECLARE @AccountID BIGINT

SET @ACCOUNTID=6813027

-- Return PAYMENT
SELECT RF_RET_PAY_CNT,HYB_RET_PAY_CNT,RF.ACCOUNTID,RF.RETURNORDERID
FROM
(SELECT COUNT(*) HYB_RET_PAY_CNT,U.p_rfaccountid , O.PK
FROM HYBRIS.DBO.PAYMENTTRANSACTIONS PT,
HYBRIS.DBO.PAYMENTINFOS PI,
HYBRIS.DBO.ORDERS O ,
HYBRIS.DBO.USERS U
WHERE PT.P_ORDER=O.PK AND PI.PK=O.PAYMENTINFOPK AND
U.P_SOURCENAME='Hybris-DM' AND U.PK=O.USERPK AND
U.P_RFACCOUNTID=CAST(@AccountID AS NVARCHAR) AND
O.TYPEPKSTRING =8796127723602 --AND O.PK=13528093
GROUP BY U.p_rfaccountid , O.PK) HYB,
(SELECT AB.ACCOUNTID,RO.RETURNORDERID , COUNT(*) RF_RET_PAY_CNT
from 
rfoperations.hybris.returnpayment RP,
rfoperations.hybris.returnorder RO,
RFOPERATIONS.RFO_ACCOUNTS.ACCOUNTBASE AB
WHERE RP.RETURNORDERID=RO.RETURNORDERID AND
AB.ACCOUNTID=@AccountID AND AB.COUNTRYID=236 AND
AB.ACCOUNTID=RO.ACCOUNTID AND RO.RETURNSTATUSID IN (1,5) AND
RO.ORDERID IN (SELECT ORDERID FROM RFOPERATIONS.ETL.ORDERDATE WHERE STARTDATE>'2014-05-01 00:00:00.00') AND
CAST(AB.ACCOUNTID AS NVARCHAR) IN (SELECT P_RFACCOUNTID FROM HYBRIS.DBO.USERS WHERE P_SOURCENAME='Hybris-DM')
GROUP BY AB.ACCOUNTID,RO.RETURNORDERID ) RF
WHERE RF.ACCOUNTID=HYB.P_RFACCOUNTID AND RF.RETURNORDERID=HYB.PK

