DECLARE @AccountID BIGINT

SET @ACCOUNTID=6813027


--Comparison of Return Order Count in RF Vs Hybris.

SELECT A.ACCOUNTID , RF_RET_STATUS AS RETURN_ORDER_STATUS , RF_RET_ORDER_CNT 'Return Order Count in RFO', HYB_RET_ORDER_CNT 'Return Order Count in HYB'
FROM
(SELECT A.ACCOUNTID,COUNT(DISTINCT O.returnORDERID) RF_RET_ORDER_CNT,
CASE RS.NAME 
	WHEN 'PROCESSED' THEN 'COMPLETED'
	WHEN 'SUBMITTED' THEN 'COMPLETED'
	WHEN 'WAIT' THEN 'TRANSIENT'
	ELSE 'UNKNOWN'
	END AS RF_RET_STATUS
FROM
rfoperations.HYBRIS.RETURNorder O,
RFOPERATIONS.rfo_reference.RETURNstatus RS,
rfoperations.RFO_ACCOUNTS.ACCOUNTBASE A
WHERE 
O.ACCOUNTID=A.ACCOUNTID AND O.ACCOUNTID IN (SELECT P_RFACCOUNTID FROM HYBRIS.DBO.USERS WHERE P_SOURCENAME='Hybris-DM') 
AND A.ACCOUNTID=@AccountID AND A.COUNTRYID=236 
AND O.RETURNSTATUSID=RS.RETURNSTATUSID AND 
ORDERID IN (SELECT ORDERID FROM RFOPERATIONS.ETL.ORDERDATE WHERE STARTDATE > '2014-05-01 00:00:00.00')
GROUP BY A.ACCOUNTID , RS.NAME) A ,
-- Count of Return orders per account in Hybris.
(SELECT U.P_RFACCOUNTID, EV.CODE , COUNT(DISTINCT O.PK) HYB_RET_ORDER_CNT
 FROM HYBRIS.DBO.ORDERS O,
 HYBRIS.DBO.USERS U,
 HYBRIS.DBO.ENUMERATIONVALUES EV
 WHERE O.USERPK=U.PK AND U.P_SOURCENAME='Hybris-DM'  AND O.typepkstring=8796127723602  -- Return Order Type
 AND U.P_RFACCOUNTID=CAST(@AccountID AS NVARCHAR)
 AND EV.PK=O.STATUSPK AND (P_TEMPLATE=0 OR P_TEMPLATE IS NULL)
 GROUP BY U.P_RFACCOUNTID , EV.CODE) B 
 WHERE ACCOUNTID=P_RFACCOUNTID AND CODE=RF_RET_STATUS  --AND RF_ORDER_CNT <> HYB_ORDER_CNT
ORDER BY 1
 
