DECLARE @AccountID BIGINT

SET @ACCOUNTID=6813027

--Autoship COUNT
SELECT P_RFACCOUNTID, HYB.NAME AS 'HYB Autoship Name', RF.Autoship_Name AS 'RF Autoship Name' ,  RF.Autoship_status , RF_AS_CNT , HYB_AS_CNT
FROM
(SELECT COUNT(*) RF_AS_CNT,AB.ACCOUNTID, AST.NAME Autoship_Name, A_S.NAME Autoship_status
FROM
RFOPERATIONS.HYBRIS.AUTOSHIP A,
RFOPERATIONS.RFO_ACCOUNTS.ACCOUNTBASE AB,
RFOPERATIONS.RFO_REFERENCE.AUTOSHIPSTATUS A_S,
RFOPERATIONS.RFO_REFERENCE.AUTOSHIPTYPE AST
WHERE 
A.ACTIVE=1 AND A.COUNTRYID=236 AND
AST.AUTOSHIPTYPEID=A.AUTOSHIPTYPEID AND AB.ACCOUNTID=@AccountID 
AND A_S.AUTOSHIPSTATUSID=A.AUTOSHIPSTATUSID AND A.AUTOSHIPID IN (SELECT AUTOSHIPID FROM RFOperations.Hybris.AutoshipItem
UNION
SELECT AUTOSHIPID FROM RFOperations.Hybris.AutoshipPayment
UNION
SELECT AUTOSHIPID FROM RFOperations.Hybris.AutoshipShipment
UNION
SELECT AUTOSHIPID FROM RFOperations.Hybris.AutoshipPaymentAddress
UNION
SELECT AUTOSHIPID FROM RFOperations.Hybris.AutoshipShippingAddress) AND
A.ACCOUNTID=AB.ACCOUNTID AND CAST(AB.ACCOUNTID AS NVARCHAR) IN (SELECT P_RFACCOUNTID FROM HYBRIS.DBO.USERS WHERE P_SOURCENAME='Hybris-DM')
GROUP BY AB.ACCOUNTID ,AST.NAME,A_S.NAME
) RF,
(--Hybris Autoships
SELECT COUNT(*) HYB_AS_CNT, U.P_RFACCOUNTID,
CASE CT.INTERNALCODE
 WHEN 'PCPerksOrder' THEN 'PC Auto-ship Template'
 WHEN 'CRPOrder' THEN 'Consultant Auto-ship Template'
 WHEN 'PulseOrder' THEN 'Pulse Template'
END AS NAME , EV.CODE
FROM HYBRIS.DBO.ORDERS O,
HYBRIS.DBO.USERS U,
HYBRIS.DBO.ENUMERATIONVALUES EV,
HYBRIS.DBO.composedtypes CT
WHERE 
U.PK=O.USERPK AND
U.P_SOURCENAME='Hybris-DM' AND EV.PK=O.STATUSPK AND
CT.PK=O.TYPEPKSTRING AND O.P_TEMPLATE=1 AND 
U.P_RFACCOUNTID=CAST(@AccountID AS NVARCHAR) AND
O.TYPEPKSTRING IN (8796124708946,
8796124741714,
8796124676178)
GROUP BY U.P_RFACCOUNTID,CT.INTERNALCODE , EV.CODE
) HYB
WHERE P_RFACCOUNTID=ACCOUNTID AND RF.Autoship_Name=HYB.NAME  AND UPPER(RF.Autoship_sTATUS)=HYB.code
--AND RF_AS_CNT <>HYB_AS_CNT

