DECLARE @AccountID BIGINT

SET @ACCOUNTID=6813027

-- Credit Card Information

SELECT RF.ACCOUNTID,RF_CC_CNT,HYB_CC_CNT
FROM
(SELECT pp.accountid , COUNT(*) RF_CC_CNT 
FROM RFOPERATIONS.RFO_ACCOUNTS.CREDITCARDPROFILES CCP,
RFOPERATIONS.RFO_ACCOUNTS.PAYMENTPROFILES PP ,
RFOPERATIONS.RFO_ACCOUNTS.ACCOUNTBASE AB,
RODANFIELDSLIVE.DBO.AccountPaymentMethods APM
WHERE PP.PAYMENTPROFILEID=CCP.PAYMENTPROFILEID AND pp.accountid=@AccountID AND AB.ACCOUNTID=PP.ACCOUNTID AND AB.COUNTRYID=236 
AND APM.AccountPaymentMethodID =PP.PAYMENTPROFILEID 
GROUP BY PP.ACCOUNTID) RF,
(SELECT COUNT(*) HYB_CC_CNT,U.p_rfaccountid FROM HYBRIS.DBO.PAYMENTINFOS PI,
HYBRIS.DBO.USERS U
WHERE PI.USERPK=U.PK AND U.P_SOURCENAME='Hybris-DM' AND PI.P_SOURCENAME='Hybris-DM' AND U.P_RFACCOUNTID=CAST(@AccountId as nvarchar) AND PI.DUPLICATE=0
GROUP BY U.p_rfaccountid) HYB
WHERE CAST(RF.ACCOUNTID AS NVARCHAR) = HYB.P_RFACCOUNTID
