DECLARE @AccountID BIGINT

SET @ACCOUNTID=6813027

--Order Notes Comparison
SELECT ORDERID , RF.ACCOUNTID, RF_NOTES_CNT,HYB_NOTES_CNT  FROM
(SELECT  COUNT(*) RF_NOTES_CNT, AB.ACCOUNTID , O.ORDERID
FROM    
RFOPERATIONS.RFO_ACCOUNTS.ACCOUNTBASE AB,
RFOperations.Hybris.Orders O,
RFOperations.ETL.OrderDate OD ,  
RFOperations.Hybris.OrderNotes ONT
WHERE   
AB.ACCOUNTID=O.ACCOUNTID AND
AB.COUNTRYID=236 AND
O.ORDERID=OD.ORDERID AND
ONT.ORDERID=O.ORDERID AND
CAST(AB.ACCOUNTID AS NVARCHAR) IN (SELECT P_RFACCOUNTID FROM HYBRIS.DBO.USERS WHERE P_SOURCENAME='Hybris-DM') AND
OD.STARTDATE>'2014-05-01 00:00:00.00' AND AB.ACCOUNTID=@AccountID
GROUP BY AB.ACCOUNTID , O.ORDERID) RF,
(SELECT COUNT(*) HYB_NOTES_CNT, U.P_RFACCOUNTID, O.PK FROM
HYBRIS.DBO.USERS U,
HYBRIS.DBO.ORDERS O,
HYBRIS.DBO.ORDERNOTES ONT
WHERE
U.P_SOURCENAME='Hybris-DM'  AND
U.PK=O.USERPK AND U.P_RFACCOUNTID=CAST(@AccountID AS NVARCHAR) AND
O.PK=ONT.P_ORDER
GROUP BY U.P_RFACCOUNTID, O.PK) HYB
WHERE RF.ACCOUNTID=P_RFACCOUNTID AND HYB.PK=ORDERID 
--AND RF_NOTES_CNT <>HYB_NOTES_CNT
