DECLARE @AccountID BIGINT

SET @ACCOUNTID=6813027


-- Return Order Item Comparison
SELECT p_rfaccountid, RF.ORDERID , RF_RET_ITEM_CNT 'Return Item count per order in RFO', HYB_RET_ITEM_CNT 'Return Item count per order in HYB'
 FROM
(SELECT COUNT(*) HYB_RET_ITEM_CNT, U.P_RFACCOUNTID,O.PK
FROM
HYBRIS.DBO.USERS U,
HYBRIS.DBO.ORDERS O,
HYBRIS.DBO.ORDERENTRIES OE,
HYBRIS.DBO.RETURNENTRY RI
WHERE U.PK=O.USERPK AND OE.PK=RI.P_ORDERENTRY AND OE.ORDERPK=O.PK AND 
U.P_SOURCENAME='Hybris-DM' AND  O.TYPEPKSTRING <> 8796127723602 AND
U.P_RFACCOUNTID=CAST(@AccountID AS NVARCHAR)
GROUP BY U.P_RFACCOUNTID,O.PK) HYB,
(SELECT COUNT(*) RF_RET_ITEM_CNT,O.ORDERID,A.ACCOUNTID
FROM
RFOPERATIONS.RFO_ACCOUNTS.ACCOUNTBASE A,
RFOPERATIONS.HYBRIS.ORDERS O,
RFOPERATIONS.HYBRIS.ORDERITEM OI,
RFOPERATIONS.ETL.ORDERDATE OD,
RFOPERATIONS.HYBRIS.RETURNITEM RI
WHERE 
A.ACCOUNTID=@AccountID AND
OI.ORDERITEMID=RI.ORDERITEMID AND OI.ORDERID=OD.ORDERID AND A.COUNTRYID=236 AND
O.ACCOUNTID=A.ACCOUNTID AND CAST(O.ACCOUNTID AS NVARCHAR) IN (SELECT P_RFACCOUNTID FROM HYBRIS.DBO.USERS WHERE P_SOURCENAME='Hybris-DM') AND
OD.STARTDATE > '2014-05-01 00:00:00.00' AND OI.ORDERID=O.ORDERID GROUP BY A.ACCOUNTID , O.ORDERID) RF
WHERE HYB.P_RFACCOUNTID=RF.ACCOUNTID AND HYB.PK=RF.ORDERID 
--AND RF_ITEM_CNT <> HYB_ITEM_CNT

