
/*
Payment Profile Check.
This script will return Accounts having MULTIPLE PaymentProfiles with IsDefault=1. 
Ideally result should be 0 but if more records are returned, then it shuold be reported for analysis
*/
SELECT PP.*
FROM RFOPERATIONS.RFO_ACCOUNTS.PAYMENTPROFILES PP , RFOPERATIONS.RFO_ACCOUNTS.ACCOUNTBASE AB WHERE AB.ACCOUNTID=PP.ACCOUNTID AND IsDefault=1 AND AB.COUNTRYID=236 AND
AB.ACCOUNTID IN 
(SELECT AB.ACCOUNTID FROM RFOPERATIONS.RFO_ACCOUNTS.PAYMENTPROFILES PP , RFOPERATIONS.RFO_ACCOUNTS.ACCOUNTBASE AB WHERE AB.ACCOUNTID=PP.ACCOUNTID AND IsDefault=1 AND AB.COUNTRYID=236 GROUP BY AB.ACCOUNTID HAVING COUNT(*)>1)
--AND PP.CHANGEDBYUSER='GP-2029'
ORDER BY ACCOUNTID

/*
Biling Address Check
This script will return Accounts having MULTIPLE BillingAddresses with IsDefault=1. 
Ideally result should be 0 but if more records are returned, then it shuold be reported for analysis
*/
SELECT AB.ACCOUNTID,AD.*
FROM RFOPERATIONS.RFO_ACCOUNTS.ACCOUNTBASE AB , RFOPERATIONS.RFO_ACCOUNTS.ACCOUNTCONTACTS AC , RFOPERATIONS.RFO_ACCOUNTS.ACCOUNTCONTACTADDRESSES ACA , RFOPERATIONS.RFO_ACCOUNTS.ADDRESSES AD
WHERE AB.ACCOUNTID=AC.ACCOUNTID AND AC.ACCOUNTCONTACTID=ACA.ACCOUNTCONTACTID AND ACA.ADDRESSID=AD.ADDRESSID AND AD.ADDRESSTYPEID=3 AND AD.ISDEFAULT=1
AND AB.ACCOUNTID IN
(SELECT AB.ACCOUNTID FROM RFOPERATIONS.RFO_ACCOUNTS.ACCOUNTBASE AB , RFOPERATIONS.RFO_ACCOUNTS.ACCOUNTCONTACTS AC , RFOPERATIONS.RFO_ACCOUNTS.ACCOUNTCONTACTADDRESSES ACA , RFOPERATIONS.RFO_ACCOUNTS.ADDRESSES AD
WHERE AB.ACCOUNTID=AC.ACCOUNTID AND AC.ACCOUNTCONTACTID=ACA.ACCOUNTCONTACTID AND ACA.ADDRESSID=AD.ADDRESSID AND AD.ADDRESSTYPEID=3 AND AD.ISDEFAULT=1
GROUP BY AB.ACCOUNTID HAVING COUNT(*)>1)
ORDER BY AB.ACCOUNTID

/*
Shipping Address check
This script will return Accounts having MULTIPLE Shipping Addresses with IsDefault=1. 
Ideally result should be 0 but if more records are returned, then it shuold be reported for analysis
*/
SELECT AB.ACCOUNTID,AD.* FROM 
RFOPERATIONS.RFO_ACCOUNTS.ACCOUNTBASE AB , RFOPERATIONS.RFO_ACCOUNTS.ACCOUNTCONTACTS AC , RFOPERATIONS.RFO_ACCOUNTS.ACCOUNTCONTACTADDRESSES ACA , RFOPERATIONS.RFO_ACCOUNTS.ADDRESSES AD
WHERE AB.ACCOUNTID=AC.ACCOUNTID AND AC.ACCOUNTCONTACTID=ACA.ACCOUNTCONTACTID AND ACA.ADDRESSID=AD.ADDRESSID AND AD.ADDRESSTYPEID=2 AND AD.ISDEFAULT=1
AND AD.CHANGEDBYUSER='GP-2029' AND  AB.ACCOUNTID IN
(SELECT AB.ACCOUNTID FROM RFOPERATIONS.RFO_ACCOUNTS.ACCOUNTBASE AB , RFOPERATIONS.RFO_ACCOUNTS.ACCOUNTCONTACTS AC , RFOPERATIONS.RFO_ACCOUNTS.ACCOUNTCONTACTADDRESSES ACA , RFOPERATIONS.RFO_ACCOUNTS.ADDRESSES AD
WHERE AB.ACCOUNTID=AC.ACCOUNTID AND AC.ACCOUNTCONTACTID=ACA.ACCOUNTCONTACTID AND ACA.ADDRESSID=AD.ADDRESSID AND AD.ADDRESSTYPEID=2 AND AD.ISDEFAULT=1
GROUP BY AB.ACCOUNTID HAVING COUNT(*)>1)
ORDER BY AB.ACCOUNTID