
USE RFOperations;
SET STATISTICS TIME ON;
GO



SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

DECLARE @HYB_key VARCHAR(100) = 'code';
DECLARE @RFO_key VARCHAR(100) = 'AutoshipID';
DECLARE @sql_gen_1 NVARCHAR(MAX);
DECLARE @sql_gen_2 NVARCHAR(MAX);
DECLARE @cnt INT;
DECLARE @lt_1 INT;
DECLARE @lt_2 INT;
DECLARE @temp TABLE
    (
      test_area VARCHAR(MAX) ,
      test_type VARCHAR(MAX) ,
      rfo_column VARCHAR(MAX) ,
      hybris_column VARCHAR(MAX) ,
      hyb_key VARCHAR(MAX) ,
      hyb_value VARCHAR(MAX) ,
      rfo_key VARCHAR(MAX) ,
      rfo_value VARCHAR(MAX)
    );
	
DECLARE @StartedTime TIME;
DECLARE @EndTime TIME; 

SELECT  'Return Header Loading TempTable ' AS EntityName ,
        GETDATE() AS StartedTime;
SELECT  @StartedTime = CAST(GETDATE() AS TIME);
		 
IF OBJECT_ID('tempdb..#LoadedAutoshipID') IS NOT NULL
    DROP TABLE #LoadedAutoshipID;

SELECT    DISTINCT
        a.AutoshipID
INTO    #LoadedAutoshipID
FROM    RFOperations.Hybris.Autoship (NOLOCK) a
        INNER JOIN RodanFieldsLive.dbo.AutoshipOrders ao ON ao.TemplateOrderID = a.AutoshipID
                                                            AND ao.AccountID = a.AccountID
        INNER JOIN RFOperations.Hybris.AutoshipItem (NOLOCK) ai ON ai.AutoshipId = a.AutoshipID
        INNER JOIN RFOperations.Hybris.AutoshipPayment (NOLOCK) ap ON ap.AutoshipID = a.AutoshipID
        INNER JOIN RFOperations.Hybris.AutoshipShipment (NOLOCK) ash ON ash.AutoshipID = a.AutoshipID
        INNER JOIN RFOperations.Hybris.AutoshipPaymentAddress (NOLOCK) apa ON apa.AutoShipID = a.AutoshipID
        INNER JOIN RFOperations.Hybris.AutoshipShippingAddress (NOLOCK) asha ON asha.AutoShipID = a.AutoshipID
        INNER JOIN Hybris.dbo.users u ON a.AccountID = u.p_rfaccountid
                                         AND u.p_sourcename = 'Hybris-DM'
WHERE   a.CountryID = 236;
     --   AND a.AutoshipID NOT IN ( SELECT    AutoshipID FROM      #DuplicateAutoship );

								  

IF OBJECT_ID('tempdb..#extra') IS NOT NULL
    DROP TABLE #extra;

SELECT  ho.code
INTO    #extra
FROM    Hybris..orders ho
        JOIN Hybris..users u ON u.PK = ho.userpk
                                AND ho.p_template = 1
                                AND u.p_sourcename = 'Hybris-DM'
        JOIN Hybris..countries c ON c.PK = u.p_country
                                    AND c.isocode = 'US'
        LEFT JOIN #LoadedAutoshipID lo ON lo.AutoshipID = ho.code
WHERE   lo.AutoshipID IS NULL; 

IF OBJECT_ID('tempdb..#tempact') IS NOT NULL
    DROP TABLE #tempact;



SELECT  a.AutoShipID ,
        a.AutoshipNumber ,
        a.AccountID ,
        u.PK ,
        a.AutoshipStatusID ,
        a.AutoshipTypeID ,
        a.StartDate ,
        a.TotalTax
INTO    #tempact
FROM    RFOperations.Hybris.Autoship (NOLOCK) a
        JOIN #LoadedAutoshipID b ON a.AutoShipID = b.AutoshipID
        JOIN Hybris.dbo.users u ON a.AccountID = u.p_rfaccountid
                                   AND u.p_sourcename = 'Hybris-DM'
WHERE   a.CountryID = 236
        AND a.AutoshipNumber NOT IN (
        SELECT  a.OrderNumber
        FROM    Hybris.Orders a
                JOIN RodanFieldsLive.dbo.Orders b ON a.OrderID = b.OrderID
                                                     AND b.OrderTypeID NOT IN (
                                                     4, 5, 9 )
                                                     AND a.CountryID = 236 )
        AND a.AutoShipID NOT IN ( SELECT    code
                                  FROM      #extra )
GROUP BY a.AutoShipID ,
        a.AutoshipNumber ,
        a.AccountID ,
        u.PK ,
        a.AutoshipStatusID ,
        a.AutoshipTypeID ,
        a.StartDate ,
        a.TotalTax;


CREATE CLUSTERED INDEX as_cls1 ON #tempact (AutoshipID);
CREATE NONCLUSTERED INDEX cls2 ON #tempact(AutoshipNumber);

		
SELECT  'Autoship header Templtable load is Completed' AS EntityName ,
        GETDATE() AS CompletionTime;

SELECT  @EndTime = CAST(GETDATE() AS TIME);
SELECT  @StartedTime AS StartedTime ,
        @EndTime AS CompletionTime ,
        DATEDIFF(MINUTE, @StartedTime, @EndTime) AS [Total Time (MM)] ,
        'Autoship Header Temp Table Loading ' AS Entity; 
		
		

SELECT  'Autoship Header   Transformed Column Validation Started ' AS EntityName ,
        GETDATE() AS StartedTime;
SELECT  @StartedTime = CAST(GETDATE() AS TIME);


		 
SET @cnt = 1;
SELECT  @lt_1 = COUNT(*)
FROM    DataMigration.dbo.map_tab
WHERE   flag = 'manual'
        AND rfo_column <> @RFO_key
        AND id NOT IN ( 69, 70 ) --Data types are image on Hybris end. This value is generated by the system
        AND [owner] = '824-Autoship';
--and prev_run_err > 0

WHILE @cnt <= @lt_1
    BEGIN

        SELECT  @sql_gen_1 = 'SELECT DISTINCT  ''' + [owner]
                + ''' as test_area, ''' + flag + ''' as test_type, '''
                + [RFO_Reference Table] + ''' as rfo_column, '''
                + Hybris_Column + ''' as hybris_column, A.' + @HYB_key
                + ' as hyb_key, A.Hyb_Trans_col as hyb_value, B.' + @RFO_key
                + ' as rfo_key, B.RFO_Trans_Col as rfo_value

FROM (SELECT a.' + @HYB_key + ', ' + Hybris_Column
                + ' as Hyb_Trans_col FROM hybris.dbo.' + Hybris_Table
                + ' a, #tempact b where a.' + @HYB_key + '=b.' + @RFO_key + '
except
SELECT a.' + @RFO_key + ', ' + RFO_Column + ' as RFO_Trans_Col FROM '
                + RFO_Table + ') A  

LEFT JOIN

(SELECT a.' + @RFO_key + ', ' + RFO_Column + ' as RFO_Trans_Col FROM '
                + RFO_Table + '
except
SELECT a.' + @HYB_key + ', ' + Hybris_Column
                + ' as Hyb_Trans_col FROM hybris.dbo.' + Hybris_Table
                + ' a, #tempact b where a.' + @HYB_key + '=b.' + @RFO_key
                + ') B
ON A.' + @HYB_key + '=B.' + @RFO_key + '
UNION
SELECT DISTINCT  ''' + [owner] + ''', ''' + flag + ''', '''
                + [RFO_Reference Table] + ''', ''' + Hybris_Column + ''', A.'
                + @HYB_key + ', A.Hyb_Trans_col, B.' + @RFO_key
                + ', B.RFO_Trans_Col

FROM (SELECT a.' + @HYB_key + ', ' + Hybris_Column
                + ' as Hyb_Trans_col FROM hybris.dbo.' + Hybris_Table
                + ' a, #tempact b where a.' + @HYB_key + '=b.' + @RFO_key + '
except
SELECT a.' + @RFO_key + ', ' + RFO_Column + ' as RFO_Trans_Col FROM '
                + RFO_Table + ') A  

RIGHT JOIN

(SELECT a.' + @RFO_key + ', ' + RFO_Column + ' as RFO_Trans_Col FROM '
                + RFO_Table + '
except
SELECT a.' + @HYB_key + ', ' + Hybris_Column
                + ' as Hyb_Trans_col FROM hybris.dbo.' + Hybris_Table
                + ' a, #tempact b where a.' + @HYB_key + '=b.' + @RFO_key
                + ') B
ON A.' + @HYB_key + '=B.' + @RFO_key + ''
        FROM    ( SELECT    * ,
                            ROW_NUMBER() OVER ( ORDER BY [owner] ) rn
                  FROM      DataMigration.dbo.map_tab
                  WHERE     flag = 'manual'
--and rfo_column <> @RFO_key 
                            AND id NOT IN ( 69, 70 ) --Data types are image on Hybris end. This value is generated by the system
                            AND id NOT IN ( 3, 4, 64, 65, 66, 72 ) --order not migrated yet
--and prev_run_err > 0
                            AND [owner] = '824-Autoship'
                ) temp
        WHERE   rn = @cnt;

        PRINT @sql_gen_1;
        INSERT  INTO @temp
                ( test_area ,
                  test_type ,
                  rfo_column ,
                  hybris_column ,
                  hyb_key ,
                  hyb_value ,
                  rfo_key ,
                  rfo_value
                )
                EXEC sp_executesql @sql_gen_1;


        IF ( SELECT COUNT(*)
             FROM   @temp
           ) > 1
            BEGIN
                DECLARE @err_cnt INT;
                SELECT  @err_cnt = CASE WHEN hyb_cnt = 0 THEN rfo_cnt
                                        ELSE hyb_cnt
                                   END
                FROM    ( SELECT    COUNT(DISTINCT hyb_key) hyb_cnt ,
                                    COUNT(DISTINCT rfo_key) rfo_cnt
                          FROM      @temp
                        ) t1;

                UPDATE  a
                SET     [prev_run_err] = @err_cnt
                FROM    DataMigration.dbo.map_tab a ,
                        @temp b
                WHERE   a.hybris_column = b.hybris_column
                        AND [owner] = '824-Autoship'; 
            END;  

        INSERT  INTO DataMigration..dm_log
                SELECT TOP 5
                        test_area ,
                        test_type ,
                        rfo_column ,
                        hybris_column ,
                        hyb_key ,
                        hyb_value ,
                        rfo_key ,
                        rfo_value
                FROM    @temp
                WHERE   ( ( COALESCE(hyb_key, '~') = COALESCE(rfo_key, '~') )
                          AND ( COALESCE(hyb_value, '~') <> COALESCE(rfo_value,
                                                              '~') )
                        )
                UNION
                SELECT TOP 5
                        test_area ,
                        test_type ,
                        rfo_column ,
                        hybris_column ,
                        hyb_key ,
                        hyb_value ,
                        rfo_key ,
                        rfo_value
                FROM    @temp
                WHERE   ( ( COALESCE(hyb_key, '~') <> COALESCE(rfo_key, '~') )
                          OR ( COALESCE(hyb_value, '~') <> COALESCE(rfo_value,
                                                              '~') )
                        );

        DELETE  FROM @temp;

        SET @cnt = @cnt + 1;

    END;

UPDATE  DataMigration.dbo.map_tab
SET     [prev_run_err] = 0
WHERE   [owner] = '824-Autoship'
        AND flag = 'manual'
        AND hybris_column NOT IN ( SELECT DISTINCT
                                            hybris_column
                                   FROM     DataMigration..dm_log
                                   WHERE    test_area = '824-Autoship'
                                            AND test_type = 'manual' );





													
SELECT  'Autoship Header  Transformed Column Validation Completed' AS EntityName ,
        GETDATE() AS CompletionTime;

SELECT  @EndTime = CAST(GETDATE() AS TIME);
SELECT  @StartedTime AS StartedTime ,
        @EndTime AS CompletionTime ,
        DATEDIFF(MINUTE, @StartedTime, @EndTime) AS [Total Time (MM)] ,
        'Autoship Header   Transformed Column Validation' AS Entity; 
		
		

INSERT  INTO DataMigration.dbo.ExecResult
        SELECT  'Autoship Header ' AS Entity ,
                'Transformed' AS Types ,
                @StartedTime AS StartedTime ,
                @EndTime AS CompletionTime ,
                DATEDIFF(MINUTE, @StartedTime, @EndTime) AS [Total Time (MM)] ,
                USER_NAME() AS UserName ,
                CAST(GETDATE() AS DATE) AS RunDate;






--/*



											
--/* LastProcessingDate Vs P_lastprocessingDate */

--USE RFOperations
--GO
              
--       DECLARE @DBbackupDate DATETIME2 = ( SELECT TOP 1
--                                                    DateValue
--                                           FROM     DataMigration.dbo.Configuration
--                                           WHERE    Name = 'DBbackupdate'
--                                         )
--       DECLARE @Noofdays_LastProcessingdate INT  = ( SELECT TOP 1
--                                                            CAST(Value AS INT)
--                                                     FROM   DataMigration.dbo.Configuration
--                                                     WHERE  Name = 'Noofdays_LastProcessingdate'
--                                                   )
--          --SELECT p_lastprocessingdate FROM Hybris..orders WHERE p_template = 1 AND code = '6680341'                                                    

----Max Order Completion Date irrespective of Order status
--       SELECT   AutoShipID ,
--                MAX(O.CompletionDate) AS CompletionDate
--       INTO     #OrderCompletiondate
--       FROM     RFOperations.Hybris.Orders O WITH ( NOLOCK )
--                JOIN RFOperations.ETL.OrderDate OD ON OD.Orderid = O.OrderID
--                JOIN Hybris..users u ON u.p_rfaccountid = CAST (O.AccountID AS VARCHAR)
--       WHERE    CountryID = 236
--                AND OD.Startdate >= '2014-06-01'
--       GROUP BY AutoShipID

--              --Latest completion date being failed
--              ;
--       WITH CTE_LatestCompletiondate_Failed
--              AS ( SELECT   AutoShipID ,
--                            MAX(O.CompletionDate) AS CompletionDate
--                   FROM     RFOperations.Hybris.Orders O WITH ( NOLOCK )
--                            JOIN RFOperations.ETL.OrderDate OD ON OD.Orderid = O.OrderID
--                            JOIN Hybris..users u ON u.p_rfaccountid = CAST (O.AccountID AS VARCHAR)
--                   WHERE    CountryID = 236
--                            AND O.OrderStatusID = 1
--                            AND OD.Startdate >= '2014-06-01'  --@Date
--                   GROUP BY AutoShipID
--                 )
--        --For Failed Orders Set Completion date as Null if 5 days beyond current date 
--              UPDATE    OC
--              SET       CompletionDate = CASE WHEN DATEDIFF(DAY,
--                                                            LCF.CompletionDate,
--                                                            @DBbackupDate) < @Noofdays_LastProcessingdate
--                                              THEN LCF.CompletionDate
--                                              ELSE NULL
--                                         END
--              FROM      #OrderCompletiondate OC
--                        JOIN CTE_LatestCompletiondate_Failed LCF ON OC.AutoShipID = LCF.AutoShipID
--                                                              AND OC.CompletionDate = LCF.CompletionDate 

                                                       

--       SELECT   O.p_lastprocessingdate ,
--                OC.CompletionDate
--       FROM     Hybris..orders O
--                JOIN #OrderCompletiondate OC ON CAST(OC.AutoShipID AS VARCHAR) = O.code
--       WHERE    p_template = 1
--                AND O.p_lastprocessingdate <> OC.CompletionDate












				
--			/* p_orderCount Vs OrderCount */
--SELECT DISTINCT  '824-Autoship' as test_area, 'manual' as test_type, 'ordercount' as rfo_column, 'p_ordercount' as hybris_column, A.code as hyb_key, A.Hyb_Trans_col as hyb_value, B.AutoshipID as rfo_key, B.RFO_Trans_Col as rfo_value

--FROM (SELECT a.code, p_ordercount as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID
--except
--SELECT a.AutoshipID, coalesce(a.ordercount, 0) as RFO_Trans_Col FROM (select asp.autoshipid, asp.autoshipnumber, count(*) ordercount
--from #tempact asp,
--hybris.orders ord 
--where asp.autoshipid = ord.autoshipid 
--and ord.orderstatusid not in (1,3) 
--group by asp.autoshipid, asp.autoshipnumber)a) A  

--LEFT JOIN

--(SELECT a.AutoshipID, coalesce(a.ordercount, 0) as RFO_Trans_Col FROM (select asp.autoshipid, asp.autoshipnumber, count(*) ordercount
--from #tempact asp,
--hybris.orders ord 
--where asp.autoshipid = ord.autoshipid 
--and ord.orderstatusid not in (1,3) 
--group by asp.autoshipid, asp.autoshipnumber)a
--except
--SELECT a.code, p_ordercount as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID) B
--ON A.code=B.AutoshipID
--UNION
--SELECT DISTINCT  '824-Autoship', 'manual', 'ordercount', 'p_ordercount', A.code, A.Hyb_Trans_col, B.AutoshipID, B.RFO_Trans_Col

--FROM (SELECT a.code, p_ordercount as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID
--except
--SELECT a.AutoshipID, coalesce(a.ordercount, 0) as RFO_Trans_Col FROM (select asp.autoshipid, asp.autoshipnumber, count(*) ordercount
--from #tempact asp,
--hybris.orders ord 
--where asp.autoshipid = ord.autoshipid 
--and ord.orderstatusid not in (1,3) 
--group by asp.autoshipid, asp.autoshipnumber)a) A  

--RIGHT JOIN

--(SELECT a.AutoshipID, coalesce(a.ordercount, 0) as RFO_Trans_Col FROM (select asp.autoshipid, asp.autoshipnumber, count(*) ordercount
--from #tempact asp,
--hybris.orders ord 
--where asp.autoshipid = ord.autoshipid 
--and ord.orderstatusid not in (1,3) 
--group by asp.autoshipid, asp.autoshipnumber)a
--except
--SELECT a.code, p_ordercount as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID) B
--ON A.code=B.AutoshipID


--/* FailureCount Vs P_ccfailureCount */



--DECLARE @Date DATE='2014-05-01',@DBbackupDate DATE='2015-10-24',@Noofdays_LastProcessingdate INT =5
--SELECT  AutoShipID ,
--        MAX(O.CompletionDate) AS CompletionDate
--INTO    #OrderCompletiondate
--FROM    RFOperations.Hybris.Orders O WITH ( NOLOCK )
--        JOIN RFOperations.ETL.OrderDate OD ON OD.Orderid = O.OrderID
--        JOIN Hybris..users u ON u.p_rfaccountid = CAST (O.AccountID AS VARCHAR)
--WHERE   CountryID = 236
--        AND OD.Startdate >= @Date
--GROUP BY AutoShipID

--              --Latest completion date being failed
--              ;
--WITH    CTE_LatestCompletiondate_Failed
--          AS ( SELECT   AutoShipID ,
--                        MAX(O.CompletionDate) AS CompletionDate
--               FROM     RFOperations.Hybris.Orders O WITH ( NOLOCK )
--                        JOIN RFOperations.ETL.OrderDate OD ON OD.Orderid = O.OrderID
--                        JOIN Hybris..users u ON u.p_rfaccountid = CAST (O.AccountID AS VARCHAR)
--               WHERE    CountryID = 236
--                        AND O.OrderStatusID = 1
--                        AND OD.Startdate >= @Date
--               GROUP BY AutoShipID
--             )
--    --For Failed Orders Set Completion date as Null if 5 days beyond current date 
--              UPDATE  OC
--        SET     CompletionDate = CASE WHEN DATEDIFF(DAY, LCF.CompletionDate,
--                                                    @DBbackupDate) < @Noofdays_LastProcessingdate
--                                      THEN LCF.CompletionDate
--                                      ELSE NULL
--                                 END
--        FROM    #OrderCompletiondate OC
--                JOIN CTE_LatestCompletiondate_Failed LCF ON OC.AutoShipID = LCF.AutoShipID
--                                                            AND OC.CompletionDate = LCF.CompletionDate 

--SELECT DISTINCT  '824-Autoship' as test_area, 'manual' as test_type, 'failurecount' as rfo_column, 'p_ccfailurecount' as hybris_column, A.code as hyb_key, A.Hyb_Trans_col as hyb_value, B.AutoshipID as rfo_key, B.RFO_Trans_Col as rfo_value

--FROM (SELECT a.code, p_ccfailurecount as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID
--except
--SELECT a.AutoshipID, coalesce(a.failurecount, 0) as RFO_Trans_Col FROM (select asp.autoshipid, asp.autoshipnumber, count(*) failurecount
--from #tempact asp,
--hybris.orders ord
--where asp.autoshipid = ord.autoshipid 
--and ord.orderstatusid in (1,3) 
--group by asp.autoshipid, asp.autoshipnumber)a) A  

--LEFT JOIN

--(SELECT a.AutoshipID, coalesce(a.failurecount, 0) as RFO_Trans_Col FROM (select asp.autoshipid, asp.autoshipnumber, count(*) failurecount
--from #tempact asp,
--hybris.orders ord
--where asp.autoshipid = ord.autoshipid 
--and ord.orderstatusid in (1,3) 
--group by asp.autoshipid, asp.autoshipnumber)a
--except
--SELECT a.code, p_ccfailurecount as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID) B
--ON A.code=B.AutoshipID
--UNION
--SELECT DISTINCT  '824-Autoship', 'manual', 'failurecount', 'p_ccfailurecount', A.code, A.Hyb_Trans_col, B.AutoshipID, B.RFO_Trans_Col

--FROM (SELECT a.code, p_ccfailurecount as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID
--except
--SELECT a.AutoshipID, coalesce(a.failurecount, 0) as RFO_Trans_Col FROM (select asp.autoshipid, asp.autoshipnumber, count(*) failurecount
--from #tempact asp,
--hybris.orders ord
--where asp.autoshipid = ord.autoshipid 
--and ord.orderstatusid in (1,3) 
--group by asp.autoshipid, asp.autoshipnumber)a) A  

--RIGHT JOIN

--(SELECT a.AutoshipID, coalesce(a.failurecount, 0) as RFO_Trans_Col FROM (select asp.autoshipid, asp.autoshipnumber, count(*) failurecount
--from #tempact asp,
--hybris.orders ord
--where asp.autoshipid = ord.autoshipid 
--and ord.orderstatusid in (1,3) 
--group by asp.autoshipid, asp.autoshipnumber)a
--except
--SELECT a.code, p_ccfailurecount as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID) B
--ON A.code=B.AutoshipID


--/* Use Hybris pk from user table based on RFO accountid' as rfo_column Vs  'p_customer'  */

--SELECT DISTINCT  '824-Autoship' as test_area, 'manual' as test_type, 'Use Hybris pk from user table based on RFO accountid' as rfo_column, 'p_customer' as hybris_column, A.code as hyb_key, A.Hyb_Trans_col as hyb_value, B.AutoshipID as rfo_key, B.RFO_Trans_Col as rfo_value

--FROM (SELECT a.code, p_customer as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID
--except
--SELECT a.AutoshipID, a.pk as RFO_Trans_Col FROM #tempact a) A  

--LEFT JOIN

--(SELECT a.AutoshipID, a.pk as RFO_Trans_Col FROM #tempact a
--except
--SELECT a.code, p_customer as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID) B
--ON A.code=B.AutoshipID
--UNION
--SELECT DISTINCT  '824-Autoship', 'manual', 'Use Hybris pk from user table based on RFO accountid', 'p_customer', A.code, A.Hyb_Trans_col, B.AutoshipID, B.RFO_Trans_Col

--FROM (SELECT a.code, p_customer as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID
--except
--SELECT a.AutoshipID, a.pk as RFO_Trans_Col FROM #tempact a) A  

--RIGHT JOIN

--(SELECT a.AutoshipID, a.pk as RFO_Trans_Col FROM #tempact a
--except
--SELECT a.code, p_customer as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID) B
--ON A.code=B.AutoshipID


--/*'AutoshipPaymentID' as rfo_column Vs  'paymentinfopk'*/

--SELECT DISTINCT  '824-Autoship' as test_area, 'manual' as test_type, 'AutoshipPaymentID' as rfo_column, 'paymentinfopk' as hybris_column, A.code as hyb_key, A.Hyb_Trans_col as hyb_value, B.AutoshipID as rfo_key, B.RFO_Trans_Col as rfo_value

--FROM (SELECT a.code, paymentinfopk as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID
--except
--SELECT a.AutoshipID, a.AutoshipPaymentID as RFO_Trans_Col FROM (select a.autoshipnumber, a.autoshipid, b.autoshippaymentid
--from #tempact a
--left join hybris.AutoshipPayment b
--on a.autoshipid= b.autoshipid 

--join hybris.dbo.paymentinfos c
--on b.autoshippaymentid=c.pk
--and b.autoshipid=c.ownerpkstring
--and duplicate = 1
--group by a.autoshipnumber, a.autoshipid, b.autoshippaymentid)a) A  

--LEFT JOIN

--(SELECT a.AutoshipID, a.AutoshipPaymentID as RFO_Trans_Col FROM (select a.autoshipnumber, a.autoshipid, b.autoshippaymentid
--from #tempact a
--left join hybris.AutoshipPayment b
--on a.autoshipid= b.autoshipid 

--join hybris.dbo.paymentinfos c
--on b.autoshippaymentid=c.pk
--and b.autoshipid=c.ownerpkstring
--and duplicate = 1
--group by a.autoshipnumber, a.autoshipid, b.autoshippaymentid)a
--except
--SELECT a.code, paymentinfopk as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID) B
--ON A.code=B.AutoshipID
--UNION
--SELECT DISTINCT  '824-Autoship', 'manual', 'AutoshipPaymentID', 'paymentinfopk', A.code, A.Hyb_Trans_col, B.AutoshipID, B.RFO_Trans_Col

--FROM (SELECT a.code, paymentinfopk as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID
--except
--SELECT a.AutoshipID, a.AutoshipPaymentID as RFO_Trans_Col FROM (select a.autoshipnumber, a.autoshipid, b.autoshippaymentid
--from #tempact a
--left join hybris.AutoshipPayment b
--on a.autoshipid= b.autoshipid 

--join hybris.dbo.paymentinfos c
--on b.autoshippaymentid=c.pk
--and b.autoshipid=c.ownerpkstring
--and duplicate = 1
--group by a.autoshipnumber, a.autoshipid, b.autoshippaymentid)a) A  

--RIGHT JOIN

--(SELECT a.AutoshipID, a.AutoshipPaymentID as RFO_Trans_Col FROM (select a.autoshipnumber, a.autoshipid, b.autoshippaymentid
--from #tempact a
--left join hybris.AutoshipPayment b
--on a.autoshipid= b.autoshipid 

--join hybris.dbo.paymentinfos c
--on b.autoshippaymentid=c.pk
--and b.autoshipid=c.ownerpkstring
--and duplicate = 1
--group by a.autoshipnumber, a.autoshipid, b.autoshippaymentid)a
--except
--SELECT a.code, paymentinfopk as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID) B
--ON A.code=B.AutoshipID

--/* 'status' Vs  'statuspk' */

--SELECT DISTINCT  '824-Autoship' as test_area, 'manual' as test_type, 'status' as rfo_column, 'statuspk' as hybris_column, A.code as hyb_key, A.Hyb_Trans_col as hyb_value, B.AutoshipID as rfo_key, B.RFO_Trans_Col as rfo_value

--FROM (SELECT a.code, statuspk as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID
--except
--SELECT a.AutoshipID, a.pk as RFO_Trans_Col FROM (SELECT  t1.AutoshipNumber ,t1.AutoshipID,
--        CASE WHEN t2.Name = 'Submitted' THEN '8796135030875'
--             WHEN t2.Name = 'Cancelled' THEN '8796093284443'
--             WHEN t2.Name = 'Failed' THEN '8796135030875'
--        END AS PK
--FROM    #tempact t1 ,
--        RFO_Reference.AutoshipStatus t2 ,
--        Hybris.dbo.vEnumerationValues t3
--WHERE   t1.AutoshipStatusId = t2.AutoshipStatusId
--        AND t2.Name = t3.Value
--        AND t3.[Type] = 'orderstatus'
--GROUP BY t1.AutoshipNumber ,t1.AutoshipID,
--        CASE WHEN t2.Name = 'Submitted' THEN '8796135030875'
--             WHEN t2.Name = 'Cancelled' THEN '8796093284443'
--             WHEN t2.Name = 'Failed' THEN '8796135030875'
--        END )a) A  

--LEFT JOIN

--(SELECT a.AutoshipID, a.pk as RFO_Trans_Col FROM (SELECT  t1.AutoshipNumber ,t1.AutoshipID,
--        CASE WHEN t2.Name = 'Submitted' THEN '8796135030875'
--             WHEN t2.Name = 'Cancelled' THEN '8796093284443'
--             WHEN t2.Name = 'Failed' THEN '8796135030875'
--        END AS PK
--FROM    #tempact t1 ,
--        RFO_Reference.AutoshipStatus t2 ,
--        Hybris.dbo.vEnumerationValues t3
--WHERE   t1.AutoshipStatusId = t2.AutoshipStatusId
--        AND t2.Name = t3.Value
--        AND t3.[Type] = 'orderstatus'
--GROUP BY t1.AutoshipNumber ,t1.AutoshipID,
--        CASE WHEN t2.Name = 'Submitted' THEN '8796135030875'
--             WHEN t2.Name = 'Cancelled' THEN '8796093284443'
--             WHEN t2.Name = 'Failed' THEN '8796135030875'
--        END )a
--except
--SELECT a.code, statuspk as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID) B
--ON A.code=B.AutoshipID
--UNION
--SELECT DISTINCT  '824-Autoship', 'manual', 'status', 'statuspk', A.code, A.Hyb_Trans_col, B.AutoshipID, B.RFO_Trans_Col

--FROM (SELECT a.code, statuspk as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID
--except
--SELECT a.AutoshipID, a.pk as RFO_Trans_Col FROM (SELECT  t1.AutoshipNumber ,t1.AutoshipID,
--        CASE WHEN t2.Name = 'Submitted' THEN '8796135030875'
--             WHEN t2.Name = 'Cancelled' THEN '8796093284443'
--             WHEN t2.Name = 'Failed' THEN '8796135030875'
--        END AS PK
--FROM    #tempact t1 ,
--        RFO_Reference.AutoshipStatus t2 ,
--        Hybris.dbo.vEnumerationValues t3
--WHERE   t1.AutoshipStatusId = t2.AutoshipStatusId
--        AND t2.Name = t3.Value
--        AND t3.[Type] = 'orderstatus'
--GROUP BY t1.AutoshipNumber ,t1.AutoshipID,
--        CASE WHEN t2.Name = 'Submitted' THEN '8796135030875'
--             WHEN t2.Name = 'Cancelled' THEN '8796093284443'
--             WHEN t2.Name = 'Failed' THEN '8796135030875'
--        END )a) A  

--RIGHT JOIN

--(SELECT a.AutoshipID, a.pk as RFO_Trans_Col FROM (SELECT  t1.AutoshipNumber ,t1.AutoshipID,
--        CASE WHEN t2.Name = 'Submitted' THEN '8796135030875'
--             WHEN t2.Name = 'Cancelled' THEN '8796093284443'
--             WHEN t2.Name = 'Failed' THEN '8796135030875'
--        END AS PK
--FROM    #tempact t1 ,
--        RFO_Reference.AutoshipStatus t2 ,
--        Hybris.dbo.vEnumerationValues t3
--WHERE   t1.AutoshipStatusId = t2.AutoshipStatusId
--        AND t2.Name = t3.Value
--        AND t3.[Type] = 'orderstatus'
--GROUP BY t1.AutoshipNumber ,t1.AutoshipID,
--        CASE WHEN t2.Name = 'Submitted' THEN '8796135030875'
--             WHEN t2.Name = 'Cancelled' THEN '8796093284443'
--             WHEN t2.Name = 'Failed' THEN '8796135030875'
--        END )a
--except
--SELECT a.code, statuspk as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID) B
--ON A.code=B.AutoshipID


--/* Pk of User as Created Vs P_CreatedBy */
--SELECT DISTINCT  '824-Autoship' as test_area, 'manual' as test_type, '' as rfo_column, 'p_createdby' as hybris_column, A.code as hyb_key, A.Hyb_Trans_col as hyb_value, B.AutoshipID as rfo_key, B.RFO_Trans_Col as rfo_value

--FROM (SELECT a.code, p_createdby as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID
--except
--SELECT a.AutoshipID, a.pk as RFO_Trans_Col FROM #tempact a) A  

--LEFT JOIN

--(SELECT a.AutoshipID, a.pk as RFO_Trans_Col FROM #tempact a
--except
--SELECT a.code, p_createdby as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID) B
--ON A.code=B.AutoshipID
--UNION
--SELECT DISTINCT  '824-Autoship', 'manual', '', 'p_createdby', A.code, A.Hyb_Trans_col, B.AutoshipID, B.RFO_Trans_Col

--FROM (SELECT a.code, p_createdby as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID
--except
--SELECT a.AutoshipID, a.pk as RFO_Trans_Col FROM #tempact a) A  

--RIGHT JOIN

--(SELECT a.AutoshipID, a.pk as RFO_Trans_Col FROM #tempact a
--except
--SELECT a.code, p_createdby as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID) B
--ON A.code=B.AutoshipID


--/* Use Hybris pk from user table based on RFO accountid' Vs 'userpk' */
--SELECT DISTINCT  '824-Autoship' as test_area, 'manual' as test_type, 'Use Hybris pk from user table based on RFO accountid' as rfo_column, 'userpk' as hybris_column, A.code as hyb_key, A.Hyb_Trans_col as hyb_value, B.AutoshipID as rfo_key, B.RFO_Trans_Col as rfo_value

--FROM (SELECT a.code, userpk as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID
--except
--SELECT a.AutoshipID, a.pk as RFO_Trans_Col FROM #tempact a) A  

--LEFT JOIN

--(SELECT a.AutoshipID, a.pk as RFO_Trans_Col FROM #tempact a
--except
--SELECT a.code, userpk as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID) B
--ON A.code=B.AutoshipID
--UNION
--SELECT DISTINCT  '824-Autoship', 'manual', 'Use Hybris pk from user table based on RFO accountid', 'userpk', A.code, A.Hyb_Trans_col, B.AutoshipID, B.RFO_Trans_Col

--FROM (SELECT a.code, userpk as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID
--except
--SELECT a.AutoshipID, a.pk as RFO_Trans_Col FROM #tempact a) A  

--RIGHT JOIN

--(SELECT a.AutoshipID, a.pk as RFO_Trans_Col FROM #tempact a
--except
--SELECT a.code, userpk as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID) B
--ON A.code=B.AutoshipID


--/* 'frequency' Vs  'p_frequency' */
--SELECT DISTINCT  '824-Autoship' as test_area, 'manual' as test_type, 'frequency' as rfo_column, 'p_frequency' as hybris_column, A.code as hyb_key, A.Hyb_Trans_col as hyb_value, B.AutoshipID as rfo_key, B.RFO_Trans_Col as rfo_value

--FROM (SELECT a.code, p_frequency as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID
--except
--SELECT a.AutoshipID, case when autoshiptypeid = 1 then 8796134473819 else 8796134506587 end as RFO_Trans_Col FROM #tempact a) A  

--LEFT JOIN

--(SELECT a.AutoshipID, case when autoshiptypeid = 1 then 8796134473819 else 8796134506587 end as RFO_Trans_Col FROM #tempact a
--except
--SELECT a.code, p_frequency as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID) B
--ON A.code=B.AutoshipID
--UNION
--SELECT DISTINCT  '824-Autoship', 'manual', 'frequency', 'p_frequency', A.code, A.Hyb_Trans_col, B.AutoshipID, B.RFO_Trans_Col

--FROM (SELECT a.code, p_frequency as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID
--except
--SELECT a.AutoshipID, case when autoshiptypeid = 1 then 8796134473819 else 8796134506587 end as RFO_Trans_Col FROM #tempact a) A  

--RIGHT JOIN

--(SELECT a.AutoshipID, case when autoshiptypeid = 1 then 8796134473819 else 8796134506587 end as RFO_Trans_Col FROM #tempact a
--except
--SELECT a.code, p_frequency as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID) B
--ON A.code=B.AutoshipID



--/*  'startdate' Vs 'p_firstscheduledautoshipdate'*/
--SELECT DISTINCT  '824-Autoship' as test_area, 'manual' as test_type, 'startdate' as rfo_column, 'p_firstscheduledautoshipdate' as hybris_column, A.code as hyb_key, A.Hyb_Trans_col as hyb_value, B.AutoshipID as rfo_key, B.RFO_Trans_Col as rfo_value

--FROM (SELECT a.code, p_firstscheduledautoshipdate as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID
--except
--SELECT a.AutoshipID, case when autoshiptypeid = 1 then startdate else dateadd(month, 1, startdate) end as RFO_Trans_Col FROM #tempact a) A  

--LEFT JOIN

--(SELECT a.AutoshipID, case when autoshiptypeid = 1 then startdate else dateadd(month, 1, startdate) end as RFO_Trans_Col FROM #tempact a
--except
--SELECT a.code, p_firstscheduledautoshipdate as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID) B
--ON A.code=B.AutoshipID
--UNION
--SELECT DISTINCT  '824-Autoship', 'manual', 'startdate', 'p_firstscheduledautoshipdate', A.code, A.Hyb_Trans_col, B.AutoshipID, B.RFO_Trans_Col

--FROM (SELECT a.code, p_firstscheduledautoshipdate as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID
--except
--SELECT a.AutoshipID, case when autoshiptypeid = 1 then startdate else dateadd(month, 1, startdate) end as RFO_Trans_Col FROM #tempact a) A  

--RIGHT JOIN

--(SELECT a.AutoshipID, case when autoshiptypeid = 1 then startdate else dateadd(month, 1, startdate) end as RFO_Trans_Col FROM #tempact a
--except
--SELECT a.code, p_firstscheduledautoshipdate as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID) B
--ON A.code=B.AutoshipID


--/* 'recent consecutivedelaycount' Vs 'p_consicutivenoofdelay */
--SELECT DISTINCT  '824-Autoship' as test_area, 'manual' as test_type, 'recent consecutivedelaycount' as rfo_column, 'p_consicutivenoofdelay' as hybris_column, A.code as hyb_key, A.Hyb_Trans_col as hyb_value, B.AutoshipID as rfo_key, B.RFO_Trans_Col as rfo_value

--FROM (SELECT a.code, p_consicutivenoofdelay as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID AND a.p_consicutivenoofdelay<>0
--except
--SELECT a.AutoshipID, a.ConsecutiveDelayCount as RFO_Trans_Col FROM (select * from (select distinct autoshipid, autoshipnumber, templateid, consecutivedelaycount,
-- row_number() over (partition by templateid order by adcl.logDate desc) rn
--from #tempact asp,
-- logging.autoshipdelaycancellationlog adcl
-- where asp.autoshipid=adcl.templateid) tmp
--where tmp.rn = 1)a) A  

--LEFT JOIN

--(SELECT a.AutoshipID, a.ConsecutiveDelayCount as RFO_Trans_Col FROM (select * from (select distinct autoshipid, autoshipnumber, templateid, consecutivedelaycount,
-- row_number() over (partition by templateid order by adcl.logDate desc) rn
--from #tempact asp,
-- logging.autoshipdelaycancellationlog adcl
-- where asp.autoshipid=adcl.templateid) tmp
--where tmp.rn = 1)a
--except
--SELECT a.code, p_consicutivenoofdelay as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID AND a.p_consicutivenoofdelay<>0) B
--ON A.code=B.AutoshipID
--UNION
--SELECT DISTINCT  '824-Autoship', 'manual', 'recent consecutivedelaycount', 'p_consicutivenoofdelay', A.code, A.Hyb_Trans_col, B.AutoshipID, B.RFO_Trans_Col

--FROM (SELECT a.code, p_consicutivenoofdelay as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID AND a.p_consicutivenoofdelay<>0
--except
--SELECT a.AutoshipID, a.ConsecutiveDelayCount as RFO_Trans_Col FROM (select * from (select distinct autoshipid, autoshipnumber, templateid, consecutivedelaycount,
-- row_number() over (partition by templateid order by adcl.logDate desc) rn
--from #tempact asp,
-- logging.autoshipdelaycancellationlog adcl
-- where asp.autoshipid=adcl.templateid) tmp
--where tmp.rn = 1)a) A  

--RIGHT JOIN

--(SELECT a.AutoshipID, a.ConsecutiveDelayCount as RFO_Trans_Col FROM (select * from (select distinct autoshipid, autoshipnumber, templateid, consecutivedelaycount,
-- row_number() over (partition by templateid order by adcl.logDate desc) rn
--from #tempact asp,
-- logging.autoshipdelaycancellationlog adcl
-- where asp.autoshipid=adcl.templateid) tmp
--where tmp.rn = 1)a
--except
--SELECT a.code, p_consicutivenoofdelay as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID AND a.p_consicutivenoofdelay<>0) B
--ON A.code=B.AutoshipID

 

-- /* 'delaycount' Vs  'p_delaycount' */
-- SELECT DISTINCT
--        '824-Autoship' AS test_area ,
--        'manual' AS test_type ,
--        'delaycount' AS rfo_column ,
--        'p_delaycount' AS hybris_column ,
--        a.code AS hyb_key ,
--        a.Hyb_Trans_col AS hyb_value ,
--        B.AutoshipID AS rfo_key ,
--        B.RFO_Trans_Col AS rfo_value
-- FROM   ( SELECT    a.code ,
--                    p_delaycount AS Hyb_Trans_col
--          FROM      Hybris.dbo.orders a ,
--                    #tempact B
--          WHERE     a.code = B.AutoshipID
--                    AND a.p_delaycount <> 0
--          EXCEPT
--          SELECT    a.AutoshipID ,
--                    ISNULL(a.delayCount, 0) AS RFO_Trans_Col
--          FROM      ( SELECT    a.AutoshipID ,
--                                a.autoshipnumber ,
--                                B.delayCount ,
--                                ROW_NUMBER() OVER ( PARTITION BY B.templateId ORDER BY B.logDate DESC ) AS rn
--                      FROM      #tempact a ,
--                                Logging.autoshipDelayCancellationLog B
--                      WHERE     a.AutoshipID = B.templateid
--                                AND a.AutoshipID = 51066
--                    ) a
--          WHERE     a.rn = 1
--        ) a
--        LEFT JOIN ( SELECT  a.AutoshipID ,
--                            ISNULL(a.delayCount, 0) AS RFO_Trans_Col
--                    FROM    ( SELECT    a.AutoshipID ,
--                                        a.autoshipnumber ,
--                                        B.delayCount ,
--                                        ROW_NUMBER() OVER ( PARTITION BY B.templateId ORDER BY B.logDate DESC ) AS rn
--                              FROM      #tempact a ,
--                                        Logging.autoshipDelayCancellationLog B
--                              WHERE     a.AutoshipID = B.templateid --AND a.autoshipid=51218
--                            ) a
--                    WHERE   a.rn = 1
--                    EXCEPT
--                    SELECT  a.code ,
--                            p_delaycount AS Hyb_Trans_col
--                    FROM    Hybris.dbo.orders a ,
--                            #tempact B
--                    WHERE   a.code = B.AutoshipID
--                  ) B ON a.code = B.AutoshipID
-- UNION
-- SELECT DISTINCT
--        '824-Autoship' ,
--        'manual' ,
--        'delaycount' ,
--        'p_delaycount' ,
--        a.code ,
--        a.Hyb_Trans_col ,
--        B.AutoshipID ,
--        B.RFO_Trans_Col
-- FROM   ( SELECT    a.code ,
--                    p_delaycount AS Hyb_Trans_col
--          FROM      Hybris.dbo.orders a ,
--                    #tempact B
--          WHERE     a.code = B.AutoshipID
--                    AND a.p_delaycount <> 0
--          EXCEPT
--          SELECT    a.AutoshipID ,
--                    ISNULL(a.delayCount, 0) AS RFO_Trans_Col
--          FROM      ( SELECT    a.AutoshipID ,
--                                a.autoshipnumber ,
--                                B.delayCount ,
--                                ROW_NUMBER() OVER ( PARTITION BY B.templateId ORDER BY B.logDate DESC ) AS rn
--                      FROM      #tempact a ,
--                                Logging.autoshipDelayCancellationLog B
--                      WHERE     a.AutoshipID = B.templateid
--                                AND a.AutoshipID = 51066
--                    ) a
--          WHERE     a.rn = 1
--        ) a
--        RIGHT JOIN ( SELECT a.AutoshipID ,
--                            ISNULL(a.delayCount, 0) AS RFO_Trans_Col
--                     FROM   ( SELECT    a.AutoshipID ,
--                                        a.autoshipnumber ,
--                                        B.delayCount ,
--                                        ROW_NUMBER() OVER ( PARTITION BY B.templateId ORDER BY B.logDate DESC ) AS rn
--                              FROM      #tempact a ,
--                                        Logging.autoshipDelayCancellationLog B
--                              WHERE     a.AutoshipID = B.templateid
--                            ) a
--                     WHERE  a.rn = 1
--                     EXCEPT
--                     SELECT a.code ,
--                            p_delaycount AS Hyb_Trans_col
--                     FROM   Hybris.dbo.orders a ,
--                            #tempact B
--                     WHERE  a.code = B.AutoshipID
--                   ) B ON a.code = B.AutoshipID;


--/* 'AutoshipPaymentAddressID' Vs  'paymentaddresspk  */
--SELECT DISTINCT  '824-Autoship' as test_area, 'manual' as test_type, 'AutoshipPaymentAddressID' as rfo_column, 'paymentaddresspk' as hybris_column, A.code as hyb_key, A.Hyb_Trans_col as hyb_value, B.AutoshipID as rfo_key, B.RFO_Trans_Col as rfo_value

--FROM (SELECT a.code, paymentaddresspk as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID
--except
--SELECT a.AutoshipID, a.AutoshipPaymentAddressID as RFO_Trans_Col FROM (select a.autoshipnumber, a.autoshipid, b.AutoshipPaymentAddressID
--from #tempact a
--left join hybris.AutoshipPaymentAddress b
--on a.autoshipid= b.autoshipid)a) A  

--LEFT JOIN

--(SELECT a.AutoshipID, a.AutoshipPaymentAddressID as RFO_Trans_Col FROM (select a.autoshipnumber, a.autoshipid, b.AutoshipPaymentAddressID
--from #tempact a
--left join hybris.AutoshipPaymentAddress b
--on a.autoshipid= b.autoshipid)a
--except
--SELECT a.code, paymentaddresspk as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID) B
--ON A.code=B.AutoshipID
--UNION
--SELECT DISTINCT  '824-Autoship', 'manual', 'AutoshipPaymentAddressID', 'paymentaddresspk', A.code, A.Hyb_Trans_col, B.AutoshipID, B.RFO_Trans_Col

--FROM (SELECT a.code, paymentaddresspk as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID
--except
--SELECT a.AutoshipID, a.AutoshipPaymentAddressID as RFO_Trans_Col FROM (select a.autoshipnumber, a.autoshipid, b.AutoshipPaymentAddressID
--from #tempact a
--left join hybris.AutoshipPaymentAddress b
--on a.autoshipid= b.autoshipid)a) A  

--RIGHT JOIN

--(SELECT a.AutoshipID, a.AutoshipPaymentAddressID as RFO_Trans_Col FROM (select a.autoshipnumber, a.autoshipid, b.AutoshipPaymentAddressID
--from #tempact a
--left join hybris.AutoshipPaymentAddress b
--on a.autoshipid= b.autoshipid)a
--except
--SELECT a.code, paymentaddresspk as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID) B
--ON A.code=B.AutoshipID

--  /* 'ShippingCost' Vs  'deliverycost */
--SELECT DISTINCT  '824-Autoship' as test_area, 'manual' as test_type, 'ShippingCost' as rfo_column, 'deliverycost' as hybris_column, A.code as hyb_key, A.Hyb_Trans_col as hyb_value, B.AutoshipID as rfo_key, B.RFO_Trans_Col as rfo_value

--FROM (SELECT a.code, deliverycost as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID
--except
--SELECT a.AutoshipID, a.ShippingCost as RFO_Trans_Col FROM (select a.autoshipnumber, a.Autoshipid, coalesce(b.ShippingCost,0) as ShippingCost
--from #tempact a
--join hybris.AutoshipShipment b
--on a.autoshipid= b.autoshipid 
--group by a.autoshipnumber, a.Autoshipid, b.ShippingCost)a) A  

--LEFT JOIN

--(SELECT a.AutoshipID, a.ShippingCost as RFO_Trans_Col FROM (select a.autoshipnumber, a.Autoshipid, coalesce(b.ShippingCost,0) as ShippingCost
--from #tempact a
-- join hybris.AutoshipShipment b
--on a.autoshipid= b.autoshipid 
--group by a.autoshipnumber, a.Autoshipid, b.ShippingCost)a
--except
--SELECT a.code, deliverycost as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID) B
--ON A.code=B.AutoshipID
--UNION
--SELECT DISTINCT  '824-Autoship', 'manual', 'ShippingCost', 'deliverycost', A.code, A.Hyb_Trans_col, B.AutoshipID, B.RFO_Trans_Col

--FROM (
--SELECT a.code, deliverycost as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID
--except
--SELECT a.AutoshipID, a.ShippingCost as RFO_Trans_Col FROM (select a.autoshipnumber, a.Autoshipid, coalesce(b.ShippingCost,0) as ShippingCost
--from #tempact a
-- join hybris.AutoshipShipment b
--on a.autoshipid= b.autoshipid 
--group by a.autoshipnumber, a.Autoshipid, b.ShippingCost)a

--) A  

--RIGHT JOIN

--(
--SELECT a.AutoshipID, a.ShippingCost as RFO_Trans_Col FROM (select a.autoshipnumber, a.Autoshipid, coalesce(b.ShippingCost,0) as ShippingCost
--from #tempact a
-- join hybris.AutoshipShipment b
--on a.autoshipid= b.autoshipid 
--group by a.autoshipnumber, a.Autoshipid, b.ShippingCost)a
--except
--SELECT a.code, deliverycost as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID 
--) B
--ON A.code=B.AutoshipID


--/*  'taxvalues'Vs  'totaltaxvalue*/
--SELECT DISTINCT  '824-Autoship' as test_area, 'manual' as test_type, 'taxvalues' as rfo_column, 'totaltaxvalues' as hybris_column, A.code as hyb_key, A.Hyb_Trans_col as hyb_value, B.AutoshipID as rfo_key, B.RFO_Trans_Col as rfo_value

--FROM (SELECT a.code, totaltaxvalues as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID
--except
--SELECT a.AutoshipID, '[<TV<0_1_0_US TOTAL TAX#' + CAST(coalesce(a.totaltax, 0) AS NVARCHAR(20)) + '#true#' + '0.0' + '#USD>VT>|
--<TV<1_1_100001_US SHIPPING TAX#' + CAST(coalesce(a.TaxOnShippingCost, 0) AS NVARCHAR(20)) + '#true#'
--                + CAST(coalesce(a.TaxOnShippingCost, 0) AS NVARCHAR(20)) + '#USD>VT>|
--<TV<2_1_300001_US HANDLING TAX#'
--                + CAST(coalesce(a.TaxOnHandlingCost, 0) AS NVARCHAR(20)) + '#true#'
--                + CAST(coalesce(a.TaxOnHandlingCost, 0) AS NVARCHAR(20)) + '#USD>VT>]' as RFO_Trans_Col FROM (select distinct asp.autoshipid, asp.autoshipnumber, ash.TaxOnShippingCost, ash.TaxOnHandlingCost, asp.totaltax
--from #tempact asp
--left join hybris.autoshipshipment ash
--on asp.autoshipid=ash.autoshipid)a) A  

--LEFT JOIN

--(SELECT a.AutoshipID, '[<TV<0_1_0_US TOTAL TAX#' + CAST(coalesce(a.totaltax, 0) AS NVARCHAR(20)) + '#true#' + '0.0' + '#USD>VT>|
--<TV<1_1_100001_US SHIPPING TAX#' + CAST(coalesce(a.TaxOnShippingCost, 0) AS NVARCHAR(20)) + '#true#'
--                + CAST(coalesce(a.TaxOnShippingCost, 0) AS NVARCHAR(20)) + '#USD>VT>|
--<TV<2_1_300001_US HANDLING TAX#'
--                + CAST(coalesce(a.TaxOnHandlingCost, 0) AS NVARCHAR(20)) + '#true#'
--                + CAST(coalesce(a.TaxOnHandlingCost, 0) AS NVARCHAR(20)) + '#USD>VT>]' as RFO_Trans_Col FROM (select distinct asp.autoshipid, asp.autoshipnumber, ash.TaxOnShippingCost, ash.TaxOnHandlingCost, asp.totaltax
--from #tempact asp
--left join hybris.autoshipshipment ash
--on asp.autoshipid=ash.autoshipid)a
--except
--SELECT a.code, totaltaxvalues as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID) B
--ON A.code=B.AutoshipID
--UNION
--SELECT DISTINCT  '824-Autoship', 'manual', 'taxvalues', 'totaltaxvalues', A.code, A.Hyb_Trans_col, B.AutoshipID, B.RFO_Trans_Col

--FROM (SELECT a.code, totaltaxvalues as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID
--except
--SELECT a.AutoshipID, '[<TV<0_1_0_US TOTAL TAX#' + CAST(coalesce(a.totaltax, 0) AS NVARCHAR(20)) + '#true#' + '0.0' + '#USD>VT>|
--<TV<1_1_100001_US SHIPPING TAX#' + CAST(coalesce(a.TaxOnShippingCost, 0) AS NVARCHAR(20)) + '#true#'
--                + CAST(coalesce(a.TaxOnShippingCost, 0) AS NVARCHAR(20)) + '#USD>VT>|
--<TV<2_1_300001_US HANDLING TAX#'
--                + CAST(coalesce(a.TaxOnHandlingCost, 0) AS NVARCHAR(20)) + '#true#'
--                + CAST(coalesce(a.TaxOnHandlingCost, 0) AS NVARCHAR(20)) + '#USD>VT>]' as RFO_Trans_Col FROM (select distinct asp.autoshipid, asp.autoshipnumber, ash.TaxOnShippingCost, ash.TaxOnHandlingCost, asp.totaltax
--from #tempact asp
--left join hybris.autoshipshipment ash
--on asp.autoshipid=ash.autoshipid)a) A  

--RIGHT JOIN

--(SELECT a.AutoshipID, '[<TV<0_1_0_US TOTAL TAX#' + CAST(coalesce(a.totaltax, 0) AS NVARCHAR(20)) + '#true#' + '0.0' + '#USD>VT>|
--<TV<1_1_100001_US SHIPPING TAX#' + CAST(coalesce(a.TaxOnShippingCost, 0) AS NVARCHAR(20)) + '#true#'
--                + CAST(coalesce(a.TaxOnShippingCost, 0) AS NVARCHAR(20)) + '#USD>VT>|
--<TV<2_1_300001_US HANDLING TAX#'
--                + CAST(coalesce(a.TaxOnHandlingCost, 0) AS NVARCHAR(20)) + '#true#'
--                + CAST(coalesce(a.TaxOnHandlingCost, 0) AS NVARCHAR(20)) + '#USD>VT>]' as RFO_Trans_Col FROM (select distinct asp.autoshipid, asp.autoshipnumber, ash.TaxOnShippingCost, ash.TaxOnHandlingCost, asp.totaltax
--from #tempact asp
--left join hybris.autoshipshipment ash
--on asp.autoshipid=ash.autoshipid)a
--except
--SELECT a.code, totaltaxvalues as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID) B
--ON A.code=B.AutoshipID

 

-- /* 'HandlingCost' Vs  'handlingcost'*/
--SELECT DISTINCT  '824-Autoship' as test_area, 'manual' as test_type, 'HandlingCost' as rfo_column, 'handlingcost' as hybris_column, A.code as hyb_key, A.Hyb_Trans_col as hyb_value, B.AutoshipID as rfo_key, B.RFO_Trans_Col as rfo_value

--FROM (SELECT a.code, handlingcost as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID
--except
--SELECT a.AutoshipID, a.HandlingCost as RFO_Trans_Col FROM (select a.autoshipnumber, a.Autoshipid, coalesce(b.HandlingCost,0) as HandlingCost
--from #tempact a
-- join hybris.AutoshipShipment b
--on a.autoshipid= b.autoshipid 
--group by a.autoshipnumber, a.Autoshipid, b.HandlingCost)a) A  

--LEFT JOIN

--(SELECT a.AutoshipID, a.HandlingCost as RFO_Trans_Col FROM (select a.autoshipnumber, a.Autoshipid, coalesce(b.HandlingCost,0) as HandlingCost
--from #tempact a
--join hybris.AutoshipShipment b
--on a.autoshipid= b.autoshipid 
--group by a.autoshipnumber, a.Autoshipid, b.HandlingCost)a
--except
--SELECT a.code, handlingcost as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID) B
--ON A.code=B.AutoshipID
--UNION
--SELECT DISTINCT  '824-Autoship', 'manual', 'HandlingCost', 'handlingcost', A.code, A.Hyb_Trans_col, B.AutoshipID, B.RFO_Trans_Col

--FROM (SELECT a.code, handlingcost as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID
--except
--SELECT a.AutoshipID, a.HandlingCost as RFO_Trans_Col FROM (select a.autoshipnumber, a.Autoshipid, coalesce(b.HandlingCost,0) as HandlingCost
--from #tempact a
-- join hybris.AutoshipShipment b
--on a.autoshipid= b.autoshipid 
--group by a.autoshipnumber, a.Autoshipid, b.HandlingCost)a) A  

--RIGHT JOIN

--(SELECT a.AutoshipID, a.HandlingCost as RFO_Trans_Col FROM (select a.autoshipnumber, a.Autoshipid, coalesce(b.HandlingCost,0) as HandlingCost
--from #tempact a
-- join hybris.AutoshipShipment b
--on a.autoshipid= b.autoshipid 
--group by a.autoshipnumber, a.Autoshipid, b.HandlingCost)a
--except
--SELECT a.code, handlingcost as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID) B
--ON A.code=B.AutoshipID

--/* 'AutoshipShippingAddressID' Vs 'deliveryaddresspk'*/
--SELECT DISTINCT  '824-Autoship' as test_area, 'manual' as test_type, 'AutoshipShippingAddressID' as rfo_column, 'deliveryaddresspk' as hybris_column, A.code as hyb_key, A.Hyb_Trans_col as hyb_value, B.AutoshipID as rfo_key, B.RFO_Trans_Col as rfo_value

--FROM (SELECT a.code, deliveryaddresspk as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID
--except
--SELECT a.AutoshipID, a.AutoshipShippingAddressID as RFO_Trans_Col FROM (select a.autoshipnumber, a.autoshipid, b.AutoshipShippingAddressID
--from #tempact a
-- join hybris.AutoshipShippingAddress b
--on a.autoshipid= b.autoshipid)a) A  

--LEFT JOIN

--(SELECT a.AutoshipID, a.AutoshipShippingAddressID as RFO_Trans_Col FROM (select a.autoshipnumber, a.autoshipid, b.AutoshipShippingAddressID
--from #tempact a
-- join hybris.AutoshipShippingAddress b
--on a.autoshipid= b.autoshipid)a
--except
--SELECT a.code, deliveryaddresspk as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID) B
--ON A.code=B.AutoshipID
--UNION
--SELECT DISTINCT  '824-Autoship', 'manual', 'AutoshipShippingAddressID', 'deliveryaddresspk', A.code, A.Hyb_Trans_col, B.AutoshipID, B.RFO_Trans_Col

--FROM (SELECT a.code, deliveryaddresspk as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID
--except
--SELECT a.AutoshipID, a.AutoshipShippingAddressID as RFO_Trans_Col FROM (select a.autoshipnumber, a.autoshipid, b.AutoshipShippingAddressID
--from #tempact a
-- join hybris.AutoshipShippingAddress b
--on a.autoshipid= b.autoshipid)a) A  

--RIGHT JOIN

--(SELECT a.AutoshipID, a.AutoshipShippingAddressID as RFO_Trans_Col FROM (select a.autoshipnumber, a.autoshipid, b.AutoshipShippingAddressID
--from #tempact a
--left join hybris.AutoshipShippingAddress b
--on a.autoshipid= b.autoshipid)a
--except
--SELECT a.code, deliveryaddresspk as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID) B
--ON A.code=B.AutoshipID

--/* 'ShippingMethod' Vs  'deliverymodepk */
--SELECT DISTINCT  '824-Autoship' as test_area, 'manual' as test_type, 'ShippingMethod' as rfo_column, 'deliverymodepk' as hybris_column, A.code as hyb_key, A.Hyb_Trans_col as hyb_value, B.AutoshipID as rfo_key, B.RFO_Trans_Col as rfo_value

--FROM (
--SELECT a.code, deliverymodepk as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID
--except
--SELECT a.AutoshipID, a.ShippingMethod as RFO_Trans_Col FROM (select distinct asp.autoshipid, asp.autoshipnumber,dm.pk as shippingmethod
--from #tempact asp
-- join hybris.autoshipshipment ash
--on asp.autoshipid=ash.autoshipid
-- join [RFO_Reference].[ShippingMethod] sm
--on ash.shippingmethodid=sm.shippingmethodid
-- join hybris.[dbo].[deliverymodes] dm
--on sm.name=dm.code)a

--) A  

--LEFT JOIN

--(
--SELECT a.AutoshipID, a.ShippingMethod as RFO_Trans_Col FROM (select distinct asp.autoshipid, asp.autoshipnumber,dm.pk as shippingmethod
--from #tempact asp

-- join hybris.autoshipshipment ash
--on asp.autoshipid=ash.autoshipid

-- join [RFO_Reference].[ShippingMethod] sm
--on ash.shippingmethodid=sm.shippingmethodid

-- join hybris.[dbo].[deliverymodes] dm
--on sm.name=dm.code)a
--except
--SELECT a.code, deliverymodepk as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID

--) B
--ON A.code=B.AutoshipID
--UNION
--SELECT DISTINCT  '824-Autoship', 'manual', 'ShippingMethod', 'deliverymodepk', A.code, A.Hyb_Trans_col, B.AutoshipID, B.RFO_Trans_Col

--FROM (SELECT a.code, deliverymodepk as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID
--except
--SELECT a.AutoshipID, a.ShippingMethod as RFO_Trans_Col FROM (select distinct asp.autoshipid, asp.autoshipnumber,dm.pk as shippingmethod
--from #tempact asp
-- join hybris.autoshipshipment ash
--on asp.autoshipid=ash.autoshipid
-- join [RFO_Reference].[ShippingMethod] sm
--on ash.shippingmethodid=sm.shippingmethodid
-- join hybris.[dbo].[deliverymodes] dm
--on sm.name=dm.code)a) A  

--RIGHT JOIN

--(SELECT a.AutoshipID, a.ShippingMethod as RFO_Trans_Col FROM (select distinct asp.autoshipid, asp.autoshipnumber,dm.pk as shippingmethod
--from #tempact asp
-- join hybris.autoshipshipment ash
--on asp.autoshipid=ash.autoshipid
-- join [RFO_Reference].[ShippingMethod] sm
--on ash.shippingmethodid=sm.shippingmethodid
-- join hybris.[dbo].[deliverymodes] dm
--on sm.name=dm.code)a
--except
--SELECT a.code, deliverymodepk as Hyb_Trans_col FROM hybris.dbo.Orders a, #tempact b where a.code=b.AutoshipID) B
--ON A.code=B.AutoshipID


-- */