DECLARE @AccountID BIGINT

SET @ACCOUNTID=6813027

--Comparison of Order Count in RF Vs Hybris.
SELECT A.ACCOUNTID , RF_STATUS AS ORDER_STATUS, RF_ORDER_CNT 'Return Count in RFO' , HYB_ORDER_CNT  'Order Count in HYB'
FROM
(SELECT A.ACCOUNTID, 
CASE OS.NAME 
WHEN 'Partially Shipped' then 'PARTIALLY_SHIPPED'
else UPPER(OS.NAME)
END AS RF_STATUS,
COUNT(DISTINCT O.ORDERID) RF_ORDER_CNT
FROM
rfoperations.HYBRIS.ORDERS O,
RFOPERATIONS.rfo_reference.orderstatus OS,
rfoperations.ETL.ORDERDATE D,
rfoperations.RFO_ACCOUNTS.ACCOUNTBASE A
WHERE O.ORDERID=D.ORDERID  AND OS.ORDERSTATUSID=O.ORDERSTATUSID AND A.ACCOUNTID=@AccountID AND A.COUNTRYID=236 AND
O.ACCOUNTID=A.ACCOUNTID AND CAST(O.ACCOUNTID AS NVARCHAR) IN (SELECT P_RFACCOUNTID FROM HYBRIS.DBO.USERS WHERE P_SOURCENAME='Hybris-DM') AND
D.STARTDATE > '2014-05-01 00:00:00.00' GROUP BY A.ACCOUNTID , OS.NAME) A ,
-- Count of orders per account in Hybris.
(SELECT U.P_RFACCOUNTID, EV.CODE ,COUNT(DISTINCT O.PK) HYB_ORDER_CNT
 FROM HYBRIS.DBO.ORDERS O,
 HYBRIS.DBO.USERS U ,
 HYBRIS.DBO.ENUMERATIONVALUES EV
 WHERE O.USERPK=U.PK AND U.P_SOURCENAME='Hybris-DM' AND O.TYPEPKSTRING <> 8796127723602   
 AND U.P_RFACCOUNTID=CAST(@AccountID AS NVARCHAR) 
 AND EV.PK=O.STATUSPK AND (P_TEMPLATE=0 OR P_TEMPLATE IS NULL) 
 GROUP BY U.P_RFACCOUNTID , EV.CODE) B 
 WHERE ACCOUNTID=P_RFACCOUNTID AND RF_STATUS=CODE --AND RF_ORDER_CNT <> HYB_ORDER_CNT

