SELECT  *
FROM    RodanFieldsLive.dbo.Accounts a WITH ( NOLOCK )
WHERE   FirstName LIKE '%RFTEST%'
        AND a.SponsorID = 544031
        AND MarketID = 1; 

	-- TEST SCENARIOS FOR THIS ISSUES INCLUDES:
	/*
	1. ANY ORDERS GENERATED FROM HAVING FIRST NAME LIKE '%RFTEST%' AND A.SPONSORID=544031 AND MARKETID=1 SHOULD BE FLAGED AS TESToRDERS IN RFO.
	2.IF MODIFY ANY OTHER  ACCOUNT TO TEST ACCOUNT CONDITION ,BOOMI SHOULD FLAGE AS TESToRDERS WITHIN ETL PROCESS AND FLOW TO RFO.

	*/

	--Does this ticket cover ReturnOrder???
